# -*- coding: utf-8 -*-
"""Kopia notatnika Wyzwanie 1 z 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OxErqWrLwtSMmuUzfxbwyiZ4BCcB_mBm

# Witaj w pierwszym wyzwaniu Praktycznego Pythona!

👉 Wyzwanie na dziś: gra komputerowa!

⚠️ Najpierw zrób kopię tego dokumentu - kliknij przycisk "copy to Drive" ("skopiuj na dysk").
"""

# Aby uruchomić kod, kliknij przycisk "play" po lewej stronie.
# Sposób PRO: shift+enter
print("Cześć!")

"""# 1. Twoje pierwsze NARZĘDZIA"""

# Składnia: nazwa_funkcji ( argument1, argument2, ... )
print("Napis")

# Funkcje mogą nie tylko przyjmować ARGUMENTY, ale także ZWRACAĆ wartość.
line = input("Podaj linię tekstu: ")

print(line)

# Wiele narzędzi jest już gotowych na Twoim biurku - tak jak `print` czy `input`.
# Niektóre funkcje trzeba zaimportować - wyciągnąć je z szuflady na stół.
from random import randint

random_number = randint(1, 100)
print(random_number)

"""# 2. Takie same, a jednak inne"""

# Każda porcja informacji ma określony typ, np. liczba (int) albo napis (str).
line = input('Podaj liczbę: ')
print(line)
print(type(line))  # jakiego typu jest `line`?

# Na każdym typie danych można wykonywać inne operacje.
# `line` jest typu str (napis), więc na razie nie możemy traktować go jak liczby:
try:
    print(100 + line)
except:
    print("Wystąpił Error")

# Musimy zmienić tekst w liczbę - a właściwie STWORZYĆ nową liczbę na podstawie tekstu.
number = int(line)
print(number)
print(type(number))
print(100 + number)

"""# 3. Gdzie pojedzie pociąg?"""

# Normalnie kod jest wykonywany od góry do dołu, linia po linii.
# Jeśli jednak chcesz zrobić rozjazd, tak aby Twój pociąg pojechał w lewo lub prawo, to wykorzystaj if-else:
x = 10
if x >= 1000:
    print("Duża liczba")
else:  # (!) brak warunku
    print("Mała liczba")
print("Koniec")

# Inne OPERATORY
x = 0
if x == 0:  # (!) dwa znaki równości
    print("Jest zerem!")
if x != 0:  # != oznacza różny
    print("Nie jest zerem")

# Instrukcja while - pozwala powtarzać pewne operacje wiele razy tak długo, dopóty jest spełniony pewien warunek.
counter = 5
while counter > 0:
    print(counter)
    counter = counter - 1
print("Koniec")

"""# Wyzwanie dla Ciebie

Poniżej widzisz grę komputerową. Komputer losuje liczbę z zakresu 1-20, a zadaniem gracza jest odgadnąć tę liczbę. Za każdym razem komputer podpowiada graczowi, czy podał liczbę za małą czy za dużą.

Jeżeli utkniesz, to wycofaj wszystkie zmiany (Ctrl+Z) i wróć do początkowej wersji.
"""

print("----------------------------------")
from random import randint

answer = randint(1, 20)

guess_as_str = input("Zgadnij liczbę: ")
guess = int(guess_as_str)
while guess != answer:
    if guess < answer:
        print("Za mała!")
    else:
        print("Za duża!")
    guess_as_str = input("Zgadnij liczbę: ")
    guess = int(guess_as_str)

print("Brawo!")