# -*- coding: utf-8 -*-
"""Wyzwanie 3 z 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p8RB14CsDm1xBIp_iKIStPEYaPZ8v0V8

# Witaj w trzecim wyzwaniu Praktycznego Pythona

👉 Wyzwanie na dziś: program automatyzujący zmianę rozszerzeń wielu plików na raz.

⚠️ Najpierw zrób kopię tego dokumentu - kliknij przycisk "copy to Drive" ("skopiuj na dysk").

# 1. Chwyć w rękę te dwa nowe narzędzia!
"""

from glob import glob

files = glob('*')
print(files)

# (!) W Google Colab szuka plików i katalogów na osobnym dysku, wcale nie na Twoim!

print(glob('sample_data/*.md'))

from os import rename

old = 'sample_data/README.md'
new = 'sample_data/README.txt'
rename(old, new)

"""# 2. Powtarzam, powtarzam, powtarzam, ..."""

files = [
    'sample_data/mnist_test.csv',
    'sample_data/mnist_train_small.csv',
]

for file in files:
    print(file)

print("Koniec")

"""# 3. Co z nazwami plików?"""

file = 'sample_data/mnist_test.csv'
print(file.split('.'))

parts = file.split('.')
print('parts =', parts)  # Gdy do printa przekazujemy kilka argumentów, wtedy wyświetla je w jednej linii.

basename = parts[0]
ext = parts[1]
print('basename =', basename)
print('ext =', ext)

# Lub krócej:
basename, ext = parts
print('basename =', basename)
print('ext =', ext)

# Lub jeszcze krócej:
basename, ext = file.split('.')
print('basename =', basename)
print('ext =', ext)

"""# Wyzwanie dla Ciebie
1. W tym momencie skrypt zmienia rozszerzenie pliku zawsze na `.csv`. Pozwól użytkownikowi podać jakie ma być nowe rozszerzenie, tak samo jak może podać `pattern`.
2. Dodaj checkbox `dry_run`, który sprawi, że program wcale nie zmieni nazw plików, a jedynie wyświetli jakie zmiany by wprowadził.
"""
print("--------------------MY TASK---------------------------")
# @title  Zmiana nazw plików

from glob import glob
from os import rename

pattern = "sample_data/*.txt"  #@param {type:"string"}
extension = input("Give me extension: ")
extension = "."+extension
print("Your extension ",extension)
files = glob(pattern)
print("MOJE PLIKI",files)

for file in files:
    name, ext = file.split('.')
    new_name = name + extension
    rename(file, new_name)
    print(file, '->', new_name)
print("Koniec")