# -*- coding: utf-8 -*-
"""Wyzwanie 2 z 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eSmmYcSueitXn_oemcJgFuFioXGpWKMI

# Witaj w drugim wyzwaniu Praktycznego Pythona

👉 Wyzwanie na dziś: stwórz kantor internetowy - użytkownik może sprawdzić historyczny kurs waluty w danym dniu korzystając z wygodnego formularza.

⚠️ Najpierw zrób kopię tego dokumentu - kliknij przycisk "copy to Drive" ("skopiuj na dysk").

# 1. Jak SZYBKO zrobić formularz?
"""

# Google Colab pozwala na łatwe tworzenie formularzy.
# Wystarczy dodać komentarz #@param

text = "asdgfhgdhgfhdhfghdafdsadsafdsafdsa" #@param {type:"string"}

# Zmień typ (napis/data/checkbox etc.) klikaj ołówek po prawej stronie.

print("Zmienna text ma wartość {text}")
print(f"Zmienna text ma wartość {text}")  # włączamy string interpolation

"""# 2. Wyciągnij szufladę requests!"""

from requests import get

date = '2021-12-14'
url = f'http://api.nbp.pl/api/exchangerates/rates/a/USD/{date}/'
resp = get(url)
print(resp)
print(type(resp))  # `resp` nie jest ani napisem ani liczbą - jest czymś bardziej złożonym

# Funkcje:         nazwa_funkcji(argument1, argument2, ...)
# Metody:   obiekt.nazwa_metody(argument1, argument2, ...)

# Metoda .upper() (dostępna tylko dla napisów):
text = 'asdf'
print(text.upper())
# print(upper(text))  # ❌ metod nie możemy używać jak funkcji

print(text)
# text.print()  # ❌ funkcji nie możemy używać jak metod

# Metoda .json() (dostępna tylko dla Responses)
data = resp.json()
print(data)

"""# 3. Duuużo informacji - jak je powyciągać?"""

currencies = ['USD', 'EUR', 'CHF']
print(currencies)
print(currencies[0])

nested_currencies = [['USD', 'dolar amerykański'], ['EUR', 'euro']]
print(nested_currencies)
print(nested_currencies[0])
print(nested_currencies[0][0])

person = {'first_name': 'Jan', 'last_name': 'Kowalski', 'phones': ['123456789', '987654321']}
print(person)
print(person['first_name'])  # (!) dalej używamy nawiasów kwadratowych

print(person['phones'])
print(person['phones'][0])

"""# Wyzwanie dla Ciebie

1. Uzupełnij poniższy kod tak, aby wyświetlał sam kurs waluty zamiast całego `data`.
2. Wyświetl kurs waluty razem z innymi informacjami, np. tak jak poniżej:
   
   ```1 EUR = 4.6436 PLN w dniu 2021-12-14```
"""

#@title  Sprawdź historyczny kurs waluty  {"run": "auto"}
print("------------------------------------------------")
from requests import get

code = "EUR" #@param ["USD", "EUR", "CHF"]
date = "2021-12-14" #@param {type:"date"}

url = f'http://api.nbp.pl/api/exchangerates/rates/a/{code}/{date}/'

resp = get(url)
data = resp.json()

# Zadanie 1
print(data["rates"][0]["mid"])

# Zadanie 2
task_2 = data["rates"][0]["mid"]
exchange_rate = "1 EUR = " +  str(task_2) + " PLN w dniu " + str(date)

print(exchange_rate)